version: "3"
services:
  my-app:
    build: ./frontend
    container_name: Front_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  java_service:
    build: ./demo
    container_name: java_service_container
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/library
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    networks:
      - spring-network
    depends_on:
      - mysqldb
    command: ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"] # Replace "your-java-application.jar" with the name of your Java application JAR file

  mysqldb:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network:
